### ISSUE TITLE
java.lang.NoClassDefFoundError: org/jtransforms/fft/DoubleFFT_2D

### ISSUE THREAD

**Issue by caviri** [NTCColumbia/moco#2]
When I try to run the plugin with a 16-bit tiff stack and template this exception appear. I'm trying to use the 2016 release.

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52i; Java 1.8.0_172 [64-bit]; Windows Server 2016 10.0; 6965MB of 784305MB (<1%)
 
java.lang.NoClassDefFoundError: org/jtransforms/fft/DoubleFFT_2D
	at moco_.templateFFT(moco_.java:819)
	at moco_.run(moco_.java:120)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.jtransforms.fft.DoubleFFT_2D
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by caviri** [comment]
Okey, It was an error related with the jars dependecies

**Comment by maxseppo** [comment]
How did you solve this? I am running into the same exact issue.
